### ISSUE TITLE
[EPIC User Story] Text editor with modular design in sections

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#39]
### Summary:
As a user I want to have a text editor with modular design in section, so that I can create my text document easily and the personal information can be copied automatically into sections.

### Description:
There should be a full-fledged text editor with modular design in section with spelling check and automatic personal information input of data. Additionally in every section example text for every section should be able to selected. 

### Issues 
- [ ]  #36
- [ ]  #37
- [ ]  #38

### Checklist
- [ ] User story is understood 
- [ ] User story is refined
- [ ] Resources are added

### Resources:

* Mockups: [Here goes a URL to or the name of the mockup(s) in inVision];

#### Testing
* Testing URL: [Here goes a URL to the testing branch or IP];
* Staging URL: [Here goes a URL to the feature on staging];

### Notes

[Some complementary notes if necessary:]

**Comment by leoluttenberger** [comment]
Continue working on it.
